A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('bookmark_add/<int:product_id>/', views.bookmark_add, name='bookmark_add'),
	path('bookmark_remove/<int:product_id>/', views.bookmark_remove, name='bookmark_remove'),
	# path('search/<str:your_search_query>', views.search_view, name='search_view'),
	path('search/', views.search, name='search'),
	path('search/<int:category_id>' , views.searchcategory , name = 'searchcategory'),
	path('search/brand/<str:brand>', views.searchbrand, name='searchcategory'),
	path('about/',views.about,name='about'),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
	path('create/', views.order_create, name='create'),
	path('<int:order_id>/', views.detail, name='detail'),
	path('payment/<int:order_id>/<price>/', views.payment, name='payment'), #vasl be zarin pal
	path('verify/', views.verify, name='verify'), #bade pardakhat
	path('apply/<int:order_id>/', views.coupon_apply, name='coupon_apply'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddForm(forms.Form):
	quantity = forms.IntegerField(label='تعداد',min_value=1, max_value=9)

cart/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from shop.models import Product, Category
from .forms import CartAddForm
from django.views.decorators.http import require_POST
from shop.models import Bookmark
from decimal import Decimal as D
from django.db.models import Max
from django.contrib.auth.models import AbstractBaseUser

def detail(request):
	cart = Cart(request)
	return render(request, 'cart/cart2.html', {'cart':cart})

@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'])
	return redirect('cart:detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:detail')


def bookmark_add(request , product_id):
	product_find = get_object_or_404(Product, id=product_id)
	bookmark_find=Bookmark.objects.create(product = product_find ,user = request.user )
	bookmark_find.save()
	bookmarks = {
		'bookmarks': Bookmark.objects.filter(user=request.user, active =True),
	}
	# print(bookmark_find)

	return  render(request,'cart/wishlist2.html',bookmarks)


def bookmark_remove(request, product_id):

	print('bookmark remove')
	product_find = get_object_or_404(Product, id=product_id)
	bookmark_find = Bookmark.objects.get(product = product_find , user = request.user)
	bookmark_find.active = False
	bookmark_find.save()

	print(bookmark_find)

	bookmarks = {
		'bookmarks': Bookmark.objects.filter(user=request.user, active =True),
	}
	return  render(request,'cart/wishlist2.html',bookmarks)

# def search_view(request,your_search_query):
# 	print('ccvv')
# 	resualt=Product.objects.filter(Q(name__icontains=your_search_query))
# 	print(resualt)
# 	return render(request, 'cart/search.html',{'resaults':resualt})
def search(request):
	search_post = request.GET.get('search')
	resaults= Product.objects.filter(Q(name=search_post))
	return render(request, 'cart/search.html', {'resaults': resaults})
# def search_price(request):
# 	print("cccc")
# 	price1 = D(request.GET.get('min_price', 0))
# 	price2 = D(request.GET.get('max_price', 0))
#
# 	if not price2:
# 		price2 = Product.objects.aggregate(Max('price'))['price__max']
#
# 	resaults= Product.objects.filter(price__range=(price1, price2))
# 	return render(request, 'cart/search.html', {'resaults': resaults})


def about(request):
  return render(request,'cart/about.html')

def searchcategory(request,category_id):
	# search_post = request.GET.get('category')
	category = Category.objects.get(id = category_id)
	resaults = Product.objects.filter(Q(category =category))
	print(resaults)
	return  render(request , 'cart/search.html' ,  {'resaults': resaults})

def searchbrand(request , brand):
	resaults = Product.objects.filter(Q(brand = brand))
	return  render(request , 'cart/search.html' ,  {'resaults': resaults})

cart/templates/cart/about.html
 {% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container">
     <div class="row">

        <!-- Feature End-->
<p  style="margin-top:30px;text-align:right">
    توسعه اینترنت روش‌های خرید ما را به کلی دگرگون کرده است. منافع موجود در خرید اینترنتی هر روز تعداد بیشتری از مردم را به تجربه آن و ایجاد تغییر در الگوهای متداول خرید ترغیب می‏‌کند. امروز دیگر افراد این روش خرید را بیشتر منطبق بر شرایط زندگی مدرن می‏‏‏‌بینند. ویژگی‏‏‏‌ها و طبیعت خرید اینترنتی با روحیات و نیازهای رو به رشد ما هماهنگ‏‏‌تر شده است. همه سخت در حال تلاش برای پیشرفت‏‏‌های شخصی و جمعی خود هستیم.
امروزه بهای اوقات فراغت ما با وجود مشغله‏‌های روزانه بسیار گرانبها‌تر شده است. همه ما برای این اوقات برنامه ریزی فشرده‏‌تری داریم. دیگر صرف زمان‌هایی نسبتا طولانی در فعالیت‏‌های نه‌چندان با اهمیت مانند خرید و سفرهای شهری برای بسیاری از انسان‌ها اولویت خود را از دست داده است. هوشمندی انسان‌ها، آنها را مجاب می‏‌کند که با تغییر در الگوهای قدیمی و نا‏کارآمد زندگی، هوشمندانه‏‌تر و امروزی‏‌تر زندگی کنند. صرف اوقات فراغت برای تفریح، آموزش، ورزش، لذت بردن از علایق شخصی و رفع خستگی‏‏‌های روزانه اولویت بیشتری نسبت به فعالیت‌‏‏‏های وقت‌گیر و در عین حال کم اهمیت‏‏‏‌تر مانند خرید کردن دارند.
امروز دیگر برای بیشتر نیازهای روزمره راه‏ حل‏‏‏‌های جدیدتری وجود دارد، از جمله برای انتخاب و خرید کالا. دیگر کمتر کسی برای خرید کالا، بدون تحقیق و بررسی دقیق اقدام می‏‌کند.
مشتریان پیشاپیش و قبل از خرید از حق انتخاب گسترده خود و اطلاعات موجود نهایت استفاده را می‏‌برند. مشتری در دنیای امروز حق انتخاب بیشتری را طلب می‏‌کند و مایل است دقیق‏‌تر و با قطعیت بیشتری انتخاب کند. زندگی امروزی بی‏‌گمان خرید به رو‏‌ش‌های نو‏تر، هوشمندانه‏‌تر و البته لذت‏‏ بخش‏‌تری را می‏‌طلبد. از همین روست که هر روز به تعداد استفاده‏ کنندگان سرویس‌های اینترنتی و مشتریان فروشگاه‏‏‌‏های اینترنتی افزوده می‌‏‏شود.
 در دیوار بهشتی می توانید اجناس دسته دوم دانشگاه را با کیفیت و قیمت مناسب دریافت کنید
</p>

     </div>
       <h3 style=text-align:right >ویژگی های این سامانه</h3>
      <div class="row">
  <div class="feature">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-6 feature-col">
                        <div class="feature-content">
                            <i class="fab fa-cc-mastercard"></i>
                            <h2 style="text-align:center;">پرداخت مطمئن</h2>
                            <p>
                                Lorem ipsum dolor sit amet consectetur elit
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 feature-col">
                        <div class="feature-content">
                            <i class="fa fa-truck"></i>
                            <h2 style="text-align:center;">ارسال به سراسر ایران</h2>
                            <p>
                                Lorem ipsum dolor sit amet consectetur elit
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 feature-col">
                        <div class="feature-content">
                            <i class="fa fa-sync-alt"></i>
                            <h2 style="text-align:center;">ارجاع کالا در صورت خرابی</h2>
                            <p>
                                Lorem ipsum dolor sit amet consectetur elit
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 feature-col">
                        <div class="feature-content">
                            <i class="fa fa-comments"></i>
                            <h2 style="text-align:center;">پشتیبانی ۲۴ ساعته</h2>
                            <p>
                                Lorem ipsum dolor sit amet consectetur elit
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</div>
 </div>



 {% endblock %}

cart/templates/cart/bookmark.html
{% extends 'base.html' %}

{% block content %}
<table style="margin-top:30px" class="table table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">User</th>

        <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    {% for bookmark in bookmarks %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ bookmark.product.name }}</td>
         <td>{{ bookmark.product.name }}</td>
        <td>{{ bookmark.user.full_name }}</td>
        <form action="{% url 'cart:bookmark_remove' bookmark.product.id %}">
                <td><a   >حذف</a></td>
        </form>

    </tr>
    {% endfor %}
    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>

<!--    <a  style="margin-left:30px;margin-bottom:30px"href="{% url 'orders:create' %}" class="btn btn-primary">ادامه فرایند خرید</a>-->
{% endblock %}

cart/templates/cart/cart2.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
        <!-- Cart Start -->
        <div class="cart-page">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>اسم محصول</th>
                                            <th>قیمت</th>
                                            <th>تعداد</th>
                                            <th>مجموع</th>
                                            <th>حذف</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                      {% for item in cart %}
                                        <tr>
                                            <td>
                                                              <div class="img">
                                                    {% thumbnail item.product.image "300x300" as img %}
                                        <img src="{{ img.url }}" class="card-img-top">
                                        <a href="product-detail.html">
                                             {% endthumbnail %}
                                        </a>
                                                    <p>{{ item.product.name }}</p>
                                                </div>
                                            </td>
                                            <td>{{ item.price }}</td>
                                             <td>{{ item.quantity }}</td>
                                              <td>{{ item.total_price }}</td>
                                                 <td><a    href="{% url 'cart:cart_remove' item.product.id %}">
                                                                                         <i class="fa fa-trash"></i></a></td>
                                        </tr>
                                        {% endfor %}
        <td> مجموع</td>
        <td colspan="3"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-page-inner">
                            <div class="row">
                                <div class="col-md-12">
<!--                                    <div class="coupon">-->
<!--                                        <input type="text" placeholder="Coupon Code">-->
<!--                                        <button>Apply Code</button>-->
<!--                                    </div>-->
                                </div>
                                <div class="col-md-12">
                                    <div class="cart-summary">
                                        <div class="cart-content">
                                            <h1>خلاصه کارت</h1>
                                            <p>جمع<span>{{ cart.get_total_price }}</span></p>
                                            <p> هزینه ارسال<span>رایگان</span></p>
                                        </div>
                                        <div class="cart-btn">
                                      <a  class="btn btn-primery" style="margin-left:30px;margin-bottom:30px;margin-top:30px;"href="{% url 'orders:create' %}" >ادامه فرایند خرید</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart End -->
           {% endblock %}

cart/templates/cart/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- Contact Start -->
        <div class="contact">
            <div class="container-fluid">
                <div class="row">
                          <div  style="margin-bottom:30px" class="  col-lg-6">
                        <div  class=" contact-form">
                             <h2>تماس با ما</h2>
                            <form>
                                <div class="row">
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" placeholder="نام و نام خوانوادگی" />
                                    </div>
                                    <div class="col-md-6">
                                        <input type="email" class="form-control" placeholder="ایمیل" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="موضوع" />
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" rows="5" placeholder="متن پیام"></textarea>
                                </div>
                                <div><button class="btn" type="submit">ثبت و ارسال</button></div>
                            </form>
                        </div>
                    </div>





                    <div style="margin-bottom:30px"class="  col-lg-6">
                        <div class="  contact-info">
                           <h2>آدرس</h2>
                            <h3><i class="fa fa-map-marker"></i>123 Office, Los Angeles, CA, USA</h3>
                            <h3><i class="fa fa-envelope"></i>office@example.com</h3>
                            <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
<!--                    <div class="col-lg-4">-->
<!--                        <div class="contact-info">-->
<!--                            <h2>Our Store</h2>-->
<!--                            <h3><i class="fa fa-map-marker"></i>123 Store, Los Angeles, CA, USA</h3>-->
<!--                            <h3><i class="fa fa-envelope"></i>store@example.com</h3>-->
<!--                            <h3><i class="fa fa-phone"></i>+123-456-7890</h3>-->
<!--                            <div class="social">-->
<!--                                <a href=""><i class="fab fa-twitter"></i></a>-->
<!--                                <a href=""><i class="fab fa-facebook-f"></i></a>-->
<!--                                <a href=""><i class="fab fa-linkedin-in"></i></a>-->
<!--                                <a href=""><i class="fab fa-instagram"></i></a>-->
<!--                                <a href=""><i class="fab fa-youtube"></i></a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->

                </div>
            </div>
         {% endblock %}

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Total Price</th>
        <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.product }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.total_price }}</td>
        <td><a href="{% url 'cart:cart_remove' item.product.id %}">Remove</a></td>
    </tr>
    {% endfor %}
    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>

    <a href="{% url 'orders:create' %}" class="btn btn-primary">Checkout</a>

{% endblock %}

cart/templates/cart/search.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content%}


     {% for result in resaults %}
  <div class="product-view">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="product-item" >

                                    <div class="product-title">

                                          <a href="{{ result.get_absolute_url }}">{{ result.name }}</a>

                                        <div class="ratting">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>

                                    </div>
                                    <div class="product-image"  style="width:100%;height:100%;align:center;">
                                        {% thumbnail result.image "300x300" as img %}
                                        <img src="{{ img.url }}" class="card-img-top">
                                        <a href="product-detail.html">
                                             {% endthumbnail %}
                                        </a>
                                    </div>


                                    <div  style="text-align: center;" class="product-price">
                                        <h3 >{{ result.price }}<span>تومان</span></h3>
<!--                                        <a class="btn" href=""><i class="fa fa-shopping-cart"></i>Buy Now</a>-->
<!--                                            <a href="#" class="btn wishlist">-->
<!--                                            <i class="fa fa-heart"></i>-->
<!--                                              <span>(0)</span>-->
<!--                                                 </a>-->
                                    </div>

                                </div>


                            </div>
                        </div>
                    </div>
            </div>
            </div>                                                                       {% endfor %}
         {% endblock %}

cart/templates/cart/test.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <!-- Contact Start -->
        <div class="contact">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="contact-info">
                            <h2>Our Office</h2>
                            <h3><i class="fa fa-map-marker"></i>123 Office, Los Angeles, CA, USA</h3>
                            <h3><i class="fa fa-envelope"></i>office@example.com</h3>
                            <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="contact-info">
                            <h2>Our Store</h2>
                            <h3><i class="fa fa-map-marker"></i>123 Store, Los Angeles, CA, USA</h3>
                            <h3><i class="fa fa-envelope"></i>store@example.com</h3>
                            <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="contact-form">
                            <form>
                                <div class="row">
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" placeholder="Your Name" />
                                    </div>
                                    <div class="col-md-6">
                                        <input type="email" class="form-control" placeholder="Your Email" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Subject" />
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" rows="5" placeholder="Message"></textarea>
                                </div>
                                <div><button class="btn" type="submit">Send Message</button></div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3305.733248043701!2d-118.24532098539802!3d34.05071312525937!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c648fa1d4803%3A0xdec27bf11f9fd336!2s123%20S%20Los%20Angeles%20St%2C%20Los%20Angeles%2C%20CA%2090012%2C%20USA!5e0!3m2!1sen!2sbd!4v1585634930544!5m2!1sen!2sbd" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
             </div>
         {% endblock %}<!-- Contact End -->

cart/templates/cart/wishlist2.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
<!-- Wishlist Start -->
        <div class="wishlist-page">
            <div class="container-fluid">
                <div class="wishlist-page-inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>اسم محصول</th>
                                            <th>قیمت</th>
                                            <th> کاربر</th>
<!--                                            <th>Add to Cart</th>-->
                                             <th>حذف</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                       {% for bookmark in bookmarks %}
                                        <tr>
                                            <td>
                                   <div class="img">
                                                    {% thumbnail bookmark.product.image "300x300" as img %}
                                        <img src="{{ img.url }}" class="card-img-top">
                                        <a href="product-detail.html">
                                             {% endthumbnail %}
                                        </a>
                                                    <p>{{ bookmark.product.name }}</p>
                                                </div>
                                            </td>
                                            <td>{{ bookmark.product.price }}</td>
                                            <td>{{ bookmark.user.full_name }}</td>

<!--                                            <td>-->
<!--&lt;!&ndash;                                                <div class="qty">&ndash;&gt;-->
<!--&lt;!&ndash;                                                    <button class="btn-minus"><i class="fa fa-minus"></i></button>&ndash;&gt;-->
<!--&lt;!&ndash;                                                    <input type="text" value="1">&ndash;&gt;-->
<!--&lt;!&ndash;                                                    <button class="btn-plus"><i class="fa fa-plus"></i></button>&ndash;&gt;-->
<!--&lt;!&ndash;                                                </div>&ndash;&gt;-->
<!--                                            </td>-->
<!--                                            <td><button class="btn-cart">Add to Cart</button></td>-->
                                            <td>
                                                <a    href="{% url 'cart:bookmark_remove' bookmark.product.id %}">
                                                                                           <i class="fa fa-trash"></i>

                                                </a>
                                            </td>
                                        </tr>
                                      {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            {% endblock %}