A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
    path('edit_profile/', views.edit_profile, name='edit_profile1'),
    path('profile/', views.view_profile, name='view_profile_with_pk'),
	path('my_account',views.show_account,name='my_account'),
	path('contact/',views.contact,name='contact'),
	path('password/', views.user_password, name='user_password'),
	path('faq/', views.faq, name='faq'),
	path('phone_login/', views.phone_login, name='phone_login'),
	path('verify/<str:phone>/<int:rand_num>/', views.verify, name='verify')



]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import MyUserManager
from ckeditor_uploader.fields import RichTextUploadingField
class User(AbstractBaseUser):
	email = models.EmailField(max_length=100, unique=True)
	full_name = models.CharField(max_length=100)
	is_admin = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	objects = MyUserManager()
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['full_name']

	def __str__(self):
		return self.email

	def has_perm(self, perm, obj=None):
		return True

	def has_module_perms(self, app_label):
		return True

	@property
	def is_staff(self):
		return self.is_admin



	# def save_profile(sender, **kwargs):
	# 	if kwargs['created']:
	# 		p1 = Profile(user=kwargs['instance'])
	# 		p1.save()
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.TextField( null=True, blank=True)
	age = models.PositiveSmallIntegerField(null=True, blank=True)
	phone = models.PositiveIntegerField(null=True, blank=True)

class Contact(models.Model):
	email = models.EmailField(max_length=100, unique=True)
	full_name = models.CharField(max_length=100)
	subject = models.CharField(max_length=100)
	message = models.TextField(max_length=200)

class FAQ(models.Model):
 STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
 ordernumber = models.IntegerField()
 question = models.CharField(max_length=200)
 answer = models.TextField()
 status=models.CharField(max_length=10, choices=STATUS)
 create_at=models.DateTimeField(auto_now_add=True)
 update_at=models.DateTimeField(auto_now=True)
 def __str__(self):
  return self.question

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import Profile
from django import forms
from captcha.fields import CaptchaField

class UserCreationForm(forms.ModelForm):
	password1 = forms.CharField(label='password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('email', 'full_name')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
			raise forms.ValidationError('passwords must match')
		return cd['password2']

	def save(self, commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user


class UserChangeForm(forms.ModelForm):
	password = ReadOnlyPasswordHashField()

	class Meta:
		model = User
		fields = ('email', 'password', 'full_name')

	def clean_password(self):
		return self.initial['password']


class UserLoginForm(forms.Form):
	email = forms.EmailField(label="ایمیل",label_suffix='',widget=forms.EmailInput(attrs={'class':'form-control'}))
	password = forms.CharField(label="رمز عبور",label_suffix='',widget=forms.PasswordInput(attrs={'class':'form-control'}))


class UserRegistrationForm(forms.Form):
	email = forms.EmailField(label="ایمیل",label_suffix='',widget=forms.EmailInput(attrs={'class': 'form-control'}))
	full_name = forms.CharField(label="نام و نام خانوادگی",label_suffix='',widget=forms.TextInput(attrs={'class':'form-control'}))
	password = forms.CharField(label="رمز عبور",label_suffix='',widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	captcha = CaptchaField(label="",label_suffix='')

class ContactForm(forms.Form):
	full_name = forms.CharField(label="نام و نام خانوادگی",label_suffix='',widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(label="ایمیل",label_suffix='',required=True,widget=forms.EmailInput(attrs={'class': 'form-control'}))
	subject = forms.CharField(label="موضوع",label_suffix='',required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
	message = forms.CharField(label="متن پیام",label_suffix='',widget=forms.Textarea(attrs={'class':'form-control'}))

class EditProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('bio', 'age','phone')
		labels = {
			'bio': ('بیو'),
			'age':('سن'),
			'phone':('تلفن')
		}



class PhoneLoginForm(forms.Form):
	phone = forms.IntegerField(label="تلفن",label_suffix='')

	def clean_phone(self):
		phone = Profile.objects.filter(phone=self.cleaned_data['phone'])
		if not phone.exists():
			raise forms.ValidationError('This phone number does not exists')
		return self.cleaned_data['phone']


class VerifyCodeForm(forms.Form):
	code = forms.IntegerField(label="کد",label_suffix='')

accounts/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .forms import UserLoginForm, UserRegistrationForm,EditProfileForm,ContactForm,PhoneLoginForm,VerifyCodeForm
from django.contrib.auth import authenticate, login, logout,update_session_auth_hash
from django.contrib import messages
from .models import User, Profile,Contact,FAQ
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, get_connection
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import PasswordChangeForm
from random import randint
from kavenegar import *
def user_login(request):
	if request.method == 'POST':
		form = UserLoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(request, email=cd['email'], password=cd['password'])
			if user is not None:
				login(request, user)
				messages.success(request, 'you logged in successfully', 'success')
				return redirect('shop:home')
			else:
				messages.error(request, 'username or password is wrong', 'danger')
	else:
		form = UserLoginForm()
	return render(request, 'accounts/login.html', {'form':form})


def user_logout(request):
	logout(request)
	messages.success(request, 'you logged out successfully', 'success')
	return redirect('shop:home')


def user_register(request):
	if request.method == 'POST':
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = User.objects.create_user(cd['email'], cd['full_name'], cd['password'])
			user.save()
			profile = Profile.objects.create( user = user)
			profile.save()

			messages.success(request, 'you registered successfully', 'success')
			return redirect('shop:home')
	else:
		form = UserRegistrationForm()
	return render(request, 'accounts/register.html', {'form':form})

def view_profile(request, pk=None):
	user_res = request.user
	profile = Profile.objects.get(user = user_res)
	return render(request, 'accounts/profile.html', {'profile':profile})

@login_required
def edit_profile(request):
	print('asss')
	user = Profile.objects.get(user = request.user)
	if request.method == 'POST':
		form = EditProfileForm(request.POST, instance=user)
		if form.is_valid():
			form.save()
			# user.email = form.cleaned_data['email']
			user.save()
			messages.success(request, 'your profile edited successfully', 'success')
		return render(request, 'accounts/edit_profile.html' , {'form':form})
	else:
		if user is  None:
			print('aaa')
			new_profile = Profile.objects.create(user = request.user )
			new_profile.save()
		else:
			form = EditProfileForm(instance= user, initial={'email':request.user.email})
	return render(request, 'accounts/edit_profile.html', {'form':form})
@login_required
def show_account(request):
	return render(request, 'accounts/my-account.html')
def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			if form.is_valid():
				subject = form.cleaned_data['subject']
				full_name = form.cleaned_data['full_name']
				email = form.cleaned_data['email']
				message = form.cleaned_data['message']
				try:
					send_mail(subject, message, email, ['sn.mousavi77@gmail.com'])
					form= ContactForm()
				except BadHeaderError:
					return HttpResponse('Invalid header found.')
			messages.success(request, 'message sent!', 'success')
	else:
		form = ContactForm()
	return render(request, 'accounts/contact2.html', {'form':form})

def user_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			if form.is_valid():
				user = form.save()
				update_session_auth_hash(request, user)  # Important!
				messages.success(request, 'Your password was successfully updated!')
				return redirect('shop:home')
			else:
				messages.error(request, 'Please correct the error below.<br>' + str(form.errors))
				return redirect('accounts:user_password')
	else:
		form = PasswordChangeForm(request.user)
		return render(request, 'accounts/password_reset.html', {'form': form,  # 'category': category
													  })

def faq(request):
	# print('pppp')
	faq = FAQ.objects.filter(status="True").order_by("ordernumber")
	# print(faq)
	return render(request, 'accounts/faq.html',  {'faq':faq})
def phone_login(request):
	if request.method == 'POST':
		form = PhoneLoginForm(request.POST)
		if form.is_valid():
			phone = f"0{form.cleaned_data['phone']}"
			print(phone)
			rand_num = randint(1000, 9999)
			print(rand_num)
			api = KavenegarAPI('4861426E45445030577A62306A422F74354D5778443554382F72694747473556')
			params = {
				'receptor': phone,
				'template': 'verifyuser',
				'token': rand_num,
				'type': 'sms',  # sms vs call
			}
			response = api.verify_lookup(params)
			return redirect('accounts:verify', phone, rand_num)
	else:
		form = PhoneLoginForm()
	return render(request, 'accounts/phone_login.html', {'form':form})
def verify(request, phone, rand_num):
	if request.method == 'POST':
		form = VerifyCodeForm(request.POST)
		if form.is_valid():
			if rand_num == form.cleaned_data['code']:
				profile = get_object_or_404(Profile, phone=phone)
				user = get_object_or_404(User, profile__id=profile.id)
				login(request, user)
				messages.success(request, 'logged in successfully', 'success')
				return redirect('shop:home')
			else:
				messages.error(request, 'your code is wrong', 'warning')
	else:
		form = VerifyCodeForm()
	return render(request, 'accounts/verifyuser.html', {'form':form})

accounts/templates/accounts/contact2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- Contact Start -->
        <div class="contact">
            <div class="container-fluid">
                <div class="row">
                          <div  style="margin-bottom:30px" class="  col-lg-6">
                        <div  class=" contact-form">
                             <h2>تماس با ما</h2>
                            <form action="" method="post">
                                 {% csrf_token %}
                                <div class="row">
                                    <div class=" col-md-6 mx-auto">
                                         {{ form.as_p }}
                         <button class="btn" type="submit">ثبت و ارسال</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div style="margin-bottom:30px"class="  col-lg-6">
                        <div class="  contact-info">
                           <h2>آدرس</h2>
                            <h3 ><i class="fa fa-map-marker icon-align-left"></i>تهران، بزرگراه شهید چمران، خیابان یمن،ميدان شهيد شهرياری، بلوار دانشجو، دانشگاه شهيد بهشتی</h3>
                            <h3 style="text-align:left;"><i class="fa fa-envelope icon-align-left"></i>pr.office@mail.sbu.ac.ir</h3>
                            <h3 style="text-align:left"><i class="fa fa-phone icon-align-left"></i>2243192</h3>
                            <div  class="social">
                                <a   href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
<!--                    <div class="col-lg-4">-->
<!--                        <div class="contact-info">-->
<!--                            <h2>Our Store</h2>-->
<!--                            <h3><i class="fa fa-map-marker"></i>123 Store, Los Angeles, CA, USA</h3>-->
<!--                            <h3><i class="fa fa-envelope"></i>store@example.com</h3>-->
<!--                            <h3><i class="fa fa-phone"></i>+123-456-7890</h3>-->
<!--                            <div class="social">-->
<!--                                <a href=""><i class="fab fa-twitter"></i></a>-->
<!--                                <a href=""><i class="fab fa-facebook-f"></i></a>-->
<!--                                <a href=""><i class="fab fa-linkedin-in"></i></a>-->
<!--                                <a href=""><i class="fab fa-instagram"></i></a>-->
<!--                                <a href=""><i class="fab fa-youtube"></i></a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->

                </div>
            </div>
         {% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
<title>Profile</title>
{%  block content %}
<div class="container">
  <div class="row">
       <div class="col-md-8 card mb-4  mt-3 ">
       <div class="card-body">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button  class="btn btn-primary" type="submit">ثبت</button>
    </form>
    <br>

</div>
       </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/faq.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#accordion" ).accordion();
  } );
  </script>
{% endblock %}
{% block content %}
        <div class="container">
             <h3 style="text-align:right; margin-top:20px;"> سوالات متداول</h3>
            <div class="row">
                 <div class="card-body">

                <div  style="margin-bottom:180px;margin-top:20px;" class=" col-lg-12">
                <div  id="accordion" class="niloo">
                    {% for rs in faq %}
                        <h3>{{ rs.question }}</h3>
                        <div>
                            <p>
                                {{ rs.answer | safe }}
                            </p>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
        </div>
        </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
        <div class="login">
            <div class="container-fluid">
                    <div  style="margin-bottom:30px" class="  col-sm-9 col-md-7 col-lg-5 mx-auto">

                        <div class="login-form">
                               <h3> ورود</h3>
                  <form  action="" method="post">
                   {% csrf_token %}
                 {{ form.as_p}}

<!--                                       <a class=" nav-link" href="">بازیابی رمز عبور</a>-->


                      <br>
                        <a  href="{% url 'accounts:phone_login'%}">ورود با  شماره تلفن </a>
                      <br>
                      <br>
                      <button type="submit" class="btn btn-primary btn-lg"  value="Login"> ورود</button>

                       <p style="margin-top:20px;"> حساب کاربری ندارید؟<a href="{% url 'accounts:register'%}">ثبت نام کنید</a></p>



                </form>

                                    </div>

                                     </div>
                                          </div>
                                                  </div>
                                                       </div>




{% endblock %}

accounts/templates/accounts/login2.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
        <div class="login">
            <div class="container-fluid">
                    <div  style="margin-bottom:30px" class="  col-sm-9 col-md-7 col-lg-5 mx-auto">
                        <div class="login-form">
                  <form  action="" method="post">
                   {% csrf_token %}
                 {{ form.as_p}}

<!--                                       <a class=" nav-link" href="">بازیابی رمز عبور</a>-->


                      <button type="submit" class="btn btn-primary btn-lg"  value="Login"> ورود</button>


                </form>

                                    </div>

                                     </div>
                                          </div>
                                                  </div>
                                                       </div>




{% endblock %}

accounts/templates/accounts/my-account.html
<!-- My Account Start -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <div class="container">
         <div class="row">
        <div class="my-account">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                            <a class="nav-link active" id="dashboard-nav" data-toggle="pill" href="#dashboard-tab" role="tab"><i class="fa fa-tachometer-alt"></i>داشبورد</a>
                            <a class="nav-link "  href="{% url 'cart:show'%}"><i class="fa fa-shopping-bag"></i>سفارش ها</a>
<!--                            <a class="nav-link" id="payment-nav" data-toggle="pill" href="#payment-tab" role="tab"><i class="fa fa-credit-card"></i>Payment Method</a>-->
                            <a class="nav-link" id="address-nav" data-toggle="pill" href="#address-tab" role="tab"><i class="fa fa-map-marker-alt"></i>آدرس</a>
                            <a class="nav-link" id="account-nav" data-toggle="pill" href="#account-tab" role="tab"><i class="fa fa-user"></i>اطلاعات  حساب کاربری</a>
                            <a class="nav-link" href="{% url 'accounts:logout'%}"><i class="fa fa-sign-out-alt"></i>خروج</a>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="dashboard-tab" role="tabpanel" aria-labelledby="dashboard-nav">
                                <h4> داشبورد</h4>
                                <p>
                                   citur ipsum diam, at dignissim lorem tempor in. Vivamus tempor hendrerit finibus. Nulla tristique viverra nisl, sit amet bibendum ante suscipit non. Praesent in faucibus tellus, sed gravida lacus. Vivamus eu diam eros. Aliquam et sapien eget arcu rhoncus scelerisque.
                                </p>
                            </div>
                            <div class="tab-pane fade" id="orders-tab" role="tabpanel" aria-labelledby="orders-nav">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th>No</th>
                                                <th>Product</th>
                                                <th>Date</th>
                                                <th>Price</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>1</td>
                                                <td>Product Name</td>
                                                <td>01 Jan 2020</td>
                                                <td>$99</td>
                                                <td>Approved</td>
                                                <td><button class="btn">View</button></td>
                                            </tr>
                                            <tr>
                                                <td>2</td>
                                                <td>Product Name</td>
                                                <td>01 Jan 2020</td>
                                                <td>$99</td>
                                                <td>Approved</td>
                                                <td><button class="btn">View</button></td>
                                            </tr>
                                            <tr>
                                                <td>3</td>
                                                <td>Product Name</td>
                                                <td>01 Jan 2020</td>
                                                <td>$99</td>
                                                <td>Approved</td>
                                                <td><button class="btn">View</button></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="payment-tab" role="tabpanel" aria-labelledby="payment-nav">
                                <h4>Payment Method</h4>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum quam ac mi viverra dictum. In efficitur ipsum diam, at dignissim lorem tempor in. Vivamus tempor hendrerit finibus. Nulla tristique viverra nisl, sit amet bibendum ante suscipit non. Praesent in faucibus tellus, sed gravida lacus. Vivamus eu diam eros. Aliquam et sapien eget arcu rhoncus scelerisque.
                                </p> 
                            </div>
                            <div class="tab-pane fade" id="address-tab" role="tabpanel" aria-labelledby="address-nav">
                                <h4>Address</h4>
                                <div class="row">
                                    <div class="col-md-6">
                                        <h5>Payment Address</h5>
                                        <p>123 Payment Street, Los Angeles, CA</p>
                                        <p>Mobile: 012-345-6789</p>
                                        <button class="btn">Edit Address</button>
                                    </div>
                                    <div class="col-md-6">
                                        <h5>Shipping Address</h5>
                                        <p>123 Shipping Street, Los Angeles, CA</p>
                                        <p>Mobile: 012-345-6789</p>
                                        <button class="btn">Edit Address</button>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="account-tab" role="tabpanel" aria-labelledby="account-nav">
                                <h4>حساب کاربری</h4>
                                <div class="row">
                                    <div class="col-md-6">
                                        <input class="form-control" type="text" placeholder=" Name">
                                    </div>
                                    <div class="col-md-6">
                                        <input class="form-control" type="text" placeholder="Mobile">
                                    </div>
                                    <div class="col-md-12">
                                        <input class="form-control" type="text" placeholder="Address">
                                    </div>
                                    <div class="col-md-12">
                                        <button class="btn">Update Account</button>
                                        <br><br>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
         </div>
         </div>
      {% endblock %}
        <!-- My Account End -->

        

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% block content %}

  <div class="login">
            <div class="container-fluid">
                    <div  style="margin-bottom:30px" class="  col-sm-9 col-md-7 col-lg-5 mx-auto">
                        <div class="login-form">
            <!-- row -->
                          <div class="row">

                <div class="col-md-9">
                    <div class="billing-details">
                        <div class="section-title">
                            <h3 class="title">تغییر رمز عبور</h3>
                        </div>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% if field.help_text %}
                                    <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button class=" btn primary-btn" type="submit">ثبت</button>
                    </form>

                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->
            </div>
  </div>
{% endblock %}

accounts/templates/accounts/phone_login.html
{% extends 'base.html' %}

{% block content %}
    <form style="margin-top:30px;margin-left:20px ;margin-bottom:240px;" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input   style="margin-left:20px ;margin-bottom:20px" class="btn btn-primery" type="submit" value="ثبت">
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load shop_extras %}
{% block content %}
<title>Profile</title>
<div class="container">
  <div class="row">
       <div class="col-md-8 card mb-4  mt-3 ">
    <div class="card-body">
    <h1>پروفایل</h1>
    <p>نام کاربری:
        {{ user }}</p>
    <p>نام و نام خانوادگی:
        {{ user.full_name }}</p>
    <p>ایمیل:
        {{ user.email }}</p>
    <p>بیو:
        {{ profile.bio }}</p>
    <p> تلفن:
        {{ profile.phone |persian_int}}
        </p>
     <p>سن:
         {{profile.age|persian_int}}</p>
    {% if profile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">
    {% endif %}
          <a href="{% url 'accounts:edit_profile1'%}"class="btn btn-primary" type="submit">ویرایش اطلاعات</a>
          <a  href="{% url 'accounts:user_password'%}"class="btn btn-primary"> تغییر رمز عبور</a>
        </div>

</div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="login">
            <div class="container-fluid">
                   <div class=" col-sm-9 col-md-7 col-lg-5 mx-auto">
                        <div class="register-form">
                            <h3>ثبت نام</h3>
                  <form action="" method="post">
                   {% csrf_token %}
                 {{ form.as_p}}
<!--                       <div class="col-md-12">-->
<!--                                    <div class="custom-control custom-checkbox">-->
<!--                                        <input type="checkbox" class="custom-control-input" id="newaccount">-->
<!--                                        <label class="custom-control-label" for="newaccount">Keep me signed in</label>-->
<!--                                    </div>-->
<!--                                </div>-->
                      <button type="submit" class="btn btn-primary btn-lg"  value="signup">ثبت نام</button>

                </form>

                                    </div>

                                     </div>
                                          </div>
                                                  </div>







<!--<div class="container"  >-->
<!--        <div class=" card  col-sm-9 col-md-7 col-lg-5 mx-auto" style="max-width: 30rem;">-->
<!--            <div class="card-body">-->
<!--            <h2>Register Page</h2>-->
<!--            <div class="login-form">-->
<!--                  <form action="" method="post">-->
<!--                   {% csrf_token %}-->
<!--                 {{ form.as_p}}-->
<!--                      <button type="submit" class="btn btn-primary btn-lg"  value="signup">Sign up</button>-->

<!--                </form>-->
<!--                   </div>-->

<!--            </div>-->
<!--         </div>-->
<!--      </div>-->

{% endblock %}

accounts/templates/accounts/verifyuser.html
{% extends 'base.html' %}

{% block content %}
    <form   style="margin-top:30px;margin-left:20px;margin-bottom:150px;;" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input   style="margin-left:20px ;margin-bottom:20px" class="btn btn-primery "type="submit" value="ثبت">
    </form>
{% endblock %}