A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('bookmark_add/<int:product_id>/', views.bookmark_add, name='bookmark_add'),
	path('bookmark_remove/<int:product_id>/', views.bookmark_remove, name='bookmark_remove'),
	# path('search/<str:your_search_query>', views.search_view, name='search_view'),
	path('search/', views.search, name='search'),
	path('search/<int:category_id>' , views.searchcategory , name = 'searchcategory'),
	path('search/brand/<str:brand>', views.searchbrand, name='searchcategory'),
	path('about/',views.about,name='about'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
	path('', views.home, name='home'),
	path('category/<slug:slug>/', views.home, name='category_filter'),
	path('<slug:slug>/', views.product_detail, name='product_detail'),

]

shop/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.db.models import Avg
from django.views.generic import TemplateView, ListView
from django.contrib.auth.models import AbstractBaseUser
from django.db.models import Q
from django.core.validators import MaxValueValidator, MinValueValidator
class Category(models.Model): # categories
	sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True, blank=True)
	is_sub = models.BooleanField(default=False)
	name = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:category_filter', args=[self.slug,])


class Product(models.Model):
	category = models.ManyToManyField(Category, related_name='products')
	name =  models.CharField(max_length=200)
	brand= models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, unique=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d/')
	description = models.TextField()
	price = models.IntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	deleted = models.BooleanField(default= True)

	def avaregereview(self):
		reviews = Comment.objects.filter(product=self).aggregate(avarage=Avg('rate'))
		print(reviews)
		avg = 0
		if reviews["avarage"] is not None:
			avg = float(reviews["avarage"])
		return avg
	class Meta:
		ordering = ('name',)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.slug])

class Comment(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    rate = models.PositiveIntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)


class Bookmark(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='bookmark')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='bookmark_user')
    active = models.BooleanField(default=True)

    def __str__(self):
    	return 'Comment {} by {}'.format(self.product.name, self.product.id)


class Images(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title;

shop/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body','rate')

class AddCommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body','rate')
		widgets = {
			'body': forms.Textarea(attrs={'class':'form-control'}),
			'rate':forms.TextInput(attrs={'min':1,'max': '5','type': 'number'})

		}
		labels = {
			'body': ('متن'),
			'rate': ('رتبه')
		}

		error_messages = {
			'body':{
				'required': 'این فیلد اجباری است',
			}
		}
		help_texts = {
			'body':'حداکثر ۴۰۰ کلمه'
		}

class AddReplyForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from persian import persian

from accounts.models import Profile
from .models import Category, Product, Comment, Images
from cart.forms import CartAddForm
from .forms import  AddCommentForm, AddReplyForm,CommentForm
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.views.generic import ListView


def home(request, slug=None):

	products = Product.objects.filter(available=True)
	categories = Category.objects.filter(is_sub=False)
	if slug:
		category = get_object_or_404(Category, slug=slug)
		products = products.filter(category=category)
	return render(request,'shop/home.html', {'products':products, 'categories':categories})


def product_detail(request, slug):
	product = get_object_or_404(Product, slug=slug)
	# profile = Profile.objects.get(user = product.)
	comments = Comment.objects.filter(product=product)
	images = Images.objects.filter(product=product)
	form = CartAddForm()
	if request.method == 'POST':
		comment_form = AddCommentForm(request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.product = product
			new_comment.user = request.user
			# print('dddv' + new_comment.user.full_name)
			new_comment.save()
			comment_form = AddCommentForm()
			messages.success(request, 'you comment submitted successfully')

	else:
		comment_form = AddCommentForm()

	return render(request, 'shop/product_detailsv2.html',{'product': product, 'form': form, 'comments': comments, 'comment_form': comment_form, 'images': images})
# def searchcategory(request):
# 	search_post = request.GET.get('category')
# 	resaults = Product.category.objects.filter(Q(category=search_post))
# 	print(resaults)
#
# 	return  render(request , 'cart/search.html' ,  {'resaults': resaults})

shop/templates/shop/category.html
<h1>aaaaa</h1>

shop/templates/shop/comment.html
{% extends 'base.html' %}
<div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>

shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% block content %}
    <h3> name:{{ product.name }}</h3>
    <small>{{ product.created }}</small><p> price:{{ product.price }} Toman</p><br/>
    <img src="{{ product.image.url }}" alt="" width="400px" height="400px" >
    <p> description:{{ product.description }}</p><br/><br/>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add to cart">
    </form>
 <div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.user.full_name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
             <hr>
        {% endfor %}
      </div>

    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

shop/templates/shop/product_details.html
{% extends 'base.html' %}
{% load static %}
{% load shop_extras %}
{% block content %}
 <div class="container">
  <div class="row">
       <div class="col-md-8 card mb-4  mt-3 ">
       <div class="card-body">
    <h3> {{ product.name }}</h3>
    <small style="float:right;" >{{ product.created }}</small>
           <br/>
           <p style="text-align: right";> قیمت:{{  product.price|persian_int  }}  تومان</p>
           <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{{ product.image.url }}" alt="First slide"width="200px" height="200px">
    </div>
    {% for rs in images %}
    <div class="carousel-item">
      <img class="d-block w-100" src="{{ rs.image.url }}" alt="Second slide"width="200px" height="200px">
    </div>
  </div>
    {% endfor %}
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



<!--    <img src="{{ product.image.url }}" alt="" width="200px" height="200px" >-->
           <br>
    <p style="text-align: right"> توضیحات:{{ product.description }}</p><br/><br/>
<!--           <p> {{ product.avaregereview}}</p>-->
            <div class="product-rating">
                                    <i  style="color:#FFD700;" class="fa fa-star{% if product.avaregereview < 1%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700; "class="fa fa-star{% if product.avaregereview < 2%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;" class="fa fa-star{% if product.avaregereview < 3%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;" class="fa fa-star{% if product.avaregereview < 4%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;"class="fa fa-star{% if product.avaregereview < 5%}-o empty{% endif%}"></i>
                <small>({{ product.avaregereview |stringformat:".2f"}})</small>
                                </div>
           <br>
<!--          <button style="float:right;" type="button" class="btn btn-primary btn-lg"> اطلاعات تماس</button>-->
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="اضافه کردن به کارت">

    </form>
           <div class="card border-secondary mb-3 " style="max-width: 15rem;float:right">
             <div class="card-body text-dark">
                  <h6  style="text-align:right; margin-top:-10px" class="card-title">شماره تماس</h6>
                     <p  class="card-text" style="text-align:right;margin-top:-10px;">
                     {{ 23479191|persian_int}}

                        <i  class="fas fa-phone-square-alt fa-lg"></i></p>

                     </div>

                     </div>

           <form  action="{% url 'cart:bookmark_add' product.id %}" >
               <button type="submit" class="btn wishlist    ">
                                            <i class="fa fa-heart"></i>

                   </button>
           </form>

  </div>
 </div>

 </div>
 </div>
 <div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count|persian_int  }} نظرات</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            اسم: {{ comment.user.full_name }}
            <span class=" text-muted font-weight-normal">
           (  {{ comment.created_on }})
            </span>
          </p>
                 {{ comment.rate |stringformat:".2f"}}
                  <div class="product-rating">
                                    <i  style="color:#FFD700;" class="fa fa-star{% if comment.rate < 1%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700; "class="fa fa-star{% if comment.rate < 2%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;" class="fa fa-star{% if comment.rate < 3%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;" class="fa fa-star{% if comment.rate < 4%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;"class="fa fa-star{% if comment.rate < 5%}-o empty{% endif%}"></i>

                                </div>
          {{ comment.body | linebreaks }}

        </div>
             <hr>
             {% endfor %}
      </div>

    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>نظر خود را بگذارید</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">ثبت</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

shop/templates/shop/product_detailsv2.html
{% extends 'base.html' %}
{% load static %}
{% load shop_extras %}
{% block content %}
        <div class="product-detail">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="product-detail-top">
                            <div class="row align-items-center">
                                <div class="card-body">
                                    <div class="col-md-6">
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="w-100 p-3" src="{{ product.image.url }}" alt="First slide"width="200px" height="200px">
    </div>
    {% for rs in images %}
    <div class="carousel-item">
      <img class="w-100 p-3" src="{{ rs.image.url }}" alt="Second slide"width="200px" height=200px">
    </div>


  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
      {% endfor %}
        </div>
</div>
                                    </div>
                                    <div class="product-content">
                                      <h2>{{ product.name }}</h2>
                                        <small style="float:right;" >{{ product.created }}</small>
                                    <div style="margin-left:20px;"class="product-rating">
                                    <i  style="color:#FFD700;" class="fa fa-star{% if product.avaregereview < 1%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700; "class="fa fa-star{% if product.avaregereview < 2%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;" class="fa fa-star{% if product.avaregereview < 3%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;" class="fa fa-star{% if product.avaregereview < 4%}-o empty{% endif%}"></i>
                                    <i style="color:#FFD700;"class="fa fa-star{% if product.avaregereview < 5%}-o empty{% endif%}"></i>
                                 <small>({{ product.avaregereview |stringformat:".2f"}})</small>
                                </div>
                                        <h4 style="text-align: right";> قیمت:{{  product.price|persian_int  }}  تومان</h4>
                                       <form style="margin-left:20px;" action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                            {{ form }}
                               <input type="submit" value="اضافه کردن به کارت">
                                              </form>
                                           <form  style="margin-left:10px;" action="{% url 'cart:bookmark_add' product.id %}" >
               <button type="submit" class="btn wishlist    ">
                                            <i class="fa fa-heart"></i>

                   </button>
           </form>
      </div>

        <div class="card border-secondary mb-3 " style="max-width: 15rem;float:right;">
             <div class="card-body text-dark">
                  <h6  style="text-align:right; margin-top:-10px" class="card-title">شماره تماس</h6>
                     <p  class="card-text" style="text-align:right;margin-top:-10px;">
                     {{ 23479191|persian_int}}

                        <i  class="fas fa-phone-square-alt fa-lg"></i></p>

                     </div>

                     </div>
                 </div>
                                  </div>
                                </div>

                        <div class="row product-detail-bottom">
                            <div class="col-lg-12">
                                <ul class="nav nav-pills nav-justified">
                                    <li class="nav-item">
                                        <a class="nav-link active" data-toggle="pill" href="#description"> توضیحات</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="pill" href="#reviews">({{ comments.count|persian_int  }}) نظرات</a>
                                    </li>
                                </ul>
                                <div class="tab-content">
                                    <div id="description" class="container tab-pane active">
                                        <p style="text-align:right;">{{ product.description }}</p>
                                    </div>
                                    <div id="reviews" class="container tab-pane fade">
                                         {% for comment in comments %}
                                        <div style="text-align:right;" class="reviews-submitted">
                                            <div  style="text-align:right;"class="reviewer">   {{ comment.user.full_name }} <span> (  {{ comment.created_on }})</span></div>

                                        <div   style="float:right;" class="product-rating">
                                          <i  style="color:#FFD700;" class="fa fa-star{% if comment.rate < 1%}-o empty{% endif%}"></i>
                                           <i style="color:#FFD700; "class="fa fa-star{% if comment.rate < 2%}-o empty{% endif%}"></i>
                                           <i style="color:#FFD700;" class="fa fa-star{% if comment.rate < 3%}-o empty{% endif%}"></i>
                                          <i style="color:#FFD700;" class="fa fa-star{% if comment.rate < 4%}-o empty{% endif%}"></i>
                                         <i style="color:#FFD700;"class="fa fa-star{% if comment.rate < 5%}-o empty{% endif%}"></i>
                                           <small> ( {{ comment.rate |stringformat:".2f"}})</small>
                                      </div>
                                            <br>
                                       {{ comment.body | linebreaks }}
                                        </div>
                                        <hr>
                                         {% endfor %}
                                        <div class="reviews-submit">
                                            {% if new_comment %}
                                            <div class="alert alert-success" role="alert">
                                              Your comment is awaiting moderation
                                            </div>
                                         {% else %}
                             <h3>نظر خود را بگذارید</h3>
                             <form method="post" style="margin-top: 1.3em;">
                              {{ comment_form.as_p }}
                                {% csrf_token %}
                                 <button type="submit" class="btn btn-primary  btn-lg">ثبت</button>
                                 </form>
                                     {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                                </div>
                            </div>
                        </div>
                    </div>




        <!-- Brand End -->

   {% endblock content %}