A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
    path('edit_profile/', views.edit_profile, name='edit_profile1'),
    path('profile/', views.view_profile, name='view_profile_with_pk'),
	path('my_account',views.show_account,name='my_account'),
	path('contact/',views.contact,name='contact'),
	path('password/', views.user_password, name='user_password'),
	path('faq/', views.faq, name='faq'),
	path('phone_login/', views.phone_login, name='phone_login'),
	path('verify/<str:phone>/<int:rand_num>/', views.verify, name='verify')



]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('bookmark_add/<int:product_id>/', views.bookmark_add, name='bookmark_add'),
	path('bookmark_remove/<int:product_id>/', views.bookmark_remove, name='bookmark_remove'),
	# path('search/<str:your_search_query>', views.search_view, name='search_view'),
	path('search/', views.search, name='search'),
	path('search/<int:category_id>' , views.searchcategory , name = 'searchcategory'),
	path('search/brand/<str:brand>', views.searchbrand, name='searchcategory'),
	path('about/',views.about,name='about'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
	path('', views.home, name='home'),
	path('category/<slug:slug>/', views.home, name='category_filter'),
	path('<slug:slug>/', views.product_detail, name='product_detail'),

]

templates/inc/footer.html
{% load static %}
<!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h5>راه های تماس با ما</h5>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>تهران، بزرگراه شهید چمران، خیابان یمن،ميدان شهيد شهرياری، بلوار دانشجو، دانشگاه شهيد بهشتی</p>
                                <p><i class="fa fa-envelope"></i>email@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h5>دیوار بهشتی را در شبکه‌های اجتماعی دنبال کنید</h5>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2 style="text-align:left" ;>با دیوار بهشتی</h2>
                            <ul>
                                <li><a href="{% url 'cart:about'%}">درباره ما</a></li>
                                <li><a href="{% url 'accounts:contact'%}">تماس با ما </a></li>
                                <li><a href="#">پشتیبانی و قوانین</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2 style="text-align:left" ;> خدمات مشتریان</h2>
                            <ul>
                                <li><a href="{% url 'accounts:faq'%}"">پاسخ پرسش‌های پرتکرار</a></li>
<!--                                <li><a href="#"> شیوه‌های پرداخت</a></li>-->
                                <li><a href="#">شرایط بازگشت کالا</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                    <div class="row justify-content-md-center copyright">
                        <p>کلیه حقوق این سایت متعلق به  دانشگاه شهید بهشتی  می‌باشد</p>
                    </div>
                </div>
        </div>
        <!-- Footer Bottom End -->

templates/inc/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light main-nav">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>




    <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <div class="col-md-1">
                        <div  class="user">
                          <a  href="{% url 'accounts:view_profile_with_pk' %}"><i class="fa fa-user fa-lg"></i></a>
                            <i class="fas fa-grip-lines-vertical"></i>
                            <a href="{% url 'cart:detail'%}">
                                <i class="fa fa-shopping-cart fa-lg"></i>
                            </a>

                        </div>
                    </div>
   <div class="col-md-5">
        <form  style="padding: 20px;" class="form-inline" action="{% url 'cart:search' %}" method="get">
            <input   style="width:70%;text-align:right" class="form-control"  type="search" name="search" placeholder="جست و جو">
            <button  style="margin-left:10px;margin-top:-11px" class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>


        </form>
        </div>


      <ul class="navbar-nav ml-auto me-auto mb-2 mb-lg-0">


<!--                            <a href="home.html" class="nav-item nav-link">Products</a>-->
<!--                            <a href="product-detail.html" class="nav-item nav-link">Product Detail</a>-->
<!--                            <a href="cart.html" class="nav-item nav-link">کارت </a>-->
                            <a class="nav-item nav-link " href="{% url 'accounts:contact'%}">تماس با ما</a>
                             <a href="{% url 'shop:home'%}" class="nav-item nav-link active">خانه</a>
                           {% if request.user.is_authenticated %}
                         <a class="nav-item nav-link " href="{% url 'accounts:logout' %}">خروج</a>
                              {% else %}
                             <a class="nav-item nav-link " href="{% url 'accounts:login'%}">ورود</a>
                             <a class="nav-item nav-link " href="{% url 'accounts:register'%}">ثبت نام</a>
          
                          {% endif %}

      </ul>
          <div  class="col-md-3 logo">
          <a href= "{% url 'shop:home'%}">
              <p style="color:black; font-size:24px;text-align:right; margin-top:20px"><img  style="float:right"src="{%static 'img/4.jpg'%}" height="60px" alt="Logo">دیوار بهشتی</p>
                            </a>
                        </div>


    </div>

  </div>
</nav>